### ISSUE TITLE
Upload session commit not triggered for large files

### ISSUE THREAD

**Issue by cbetta** [box-community/box-javascript-sdk#31]
After some playing with the chunked upload manager I noticed that uploads seem to fail for files of a very large file size, for example 3GB and above. 

Looking at the logs, it seems like every part is uploaded, yet a the commit endpoint is never called. There seems to be no error indicating why this didn't happen. Every uploaded part seems to return a 200.

**Comment by allenmichael** [comment]
Hi there! Currently working on a fix for this. I noticed it too after you mentioned for larger files as I had only been testing with ~1GB files. Loading the file and getting the sha1 hash at the end of the uploads fails because the browser can't handle loading that much into memory, it seems. Working on an alternative way to collect the hash parts from the blobs as the individual chunks are read into memory instead.

**Comment by cbetta** [comment]
Great, thank you so much! Let me know if there's anything I can do to help.

**Comment by allenmichael** [comment]
Fixed with #32, thanks again for pointing this out!

**Comment by cbetta** [comment]
Whoop, thanks for the quick turnaround!
